[colors.primary]
background = "#282828"
foreground = "#c5c8c6"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10
