theme = 'gruvbox'

[editor]
line-number ='relative'
mouse =false

[editor.cursor-shape]
insert='bar'
normal='block'
select='underline'

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]
"C-c"= ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-c"= ["collapse_selection", "keep_primary_selection", "normal_mode"]
